name: Run tests for Remote-Vector-Index-Builder

on:
  push:
    paths:  # Note this is done for folder specific checkouts, reduce CI memory load
      - 'remote-vector-index-builder/**'
      - 'test_remote-vector-index-builder/**'
  pull_request:
    paths:  # Note this is done for folder specific checkouts, reduce CI memory load
      - 'remote-vector-index-builder/**'
      - 'test_remote-vector-index-builder/**'

permissions:
  contents: read

jobs:
  run-tests:
    name: Run tests for Remote-Vector-Index-Builder
    runs-on: ubuntu-latest
    if: github.repository == 'opensearch-project/remote-vector-index-builder'

    steps:
        # https://github.com/actions/checkout?tab=readme-ov-file#usage
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            # Note this is done for folder specific checkouts, reduce CI memory load
            sparse-checkout: |
              .github/CODEOWNERS
              remote-vector-index-builder
              test_remote-vector-index-builder
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r remote-vector-index-builder/core/requirements.txt
            python -m pip install -r test_remote-vector-index-builder/requirements.txt

        - name: Run Linting - flake8
          run: |
            python -m flake8 remote-vector-index-builder/ test_remote-vector-index-builder/

        - name: Run Formatter - black
          run: |
            python -m black --check remote-vector-index-builder/ test_remote-vector-index-builder/

        - name: Run Type Checker - mypy
          run: |
            python -m mypy remote-vector-index-builder/ test_remote-vector-index-builder/
        - name: Run tests
          run: |
            python -m pytest test_remote-vector-index-builder/
