name: Run tests for Remote-Vector-Index-Builder

on:
  push:
    paths:  # Note this is done for folder specific checkouts, reduce CI memory load
      - 'remote_vector_index_builder/**'
      - 'test_remote_vector_index_builder/**'
      - 'e2e/**'
  pull_request:
    paths:  # Note this is done for folder specific checkouts, reduce CI memory load
      - 'remote_vector_index_builder/**'
      - 'test_remote_vector_index_builder/**'
      - 'e2e/**'

permissions:
  contents: read

jobs:
  run-tests:
    name: Run tests for Remote-Vector-Index-Builder
    runs-on: ubuntu-latest
    if: github.repository == 'opensearch-project/remote-vector-index-builder'

    steps:
        # https://github.com/actions/checkout?tab=readme-ov-file#usage
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            # Note this is done for folder specific checkouts, reduce CI memory load
            sparse-checkout: |
              .github/CODEOWNERS
              remote_vector_index_builder
              test_remote_vector_index_builder
              e2e
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install -r remote_vector_index_builder/core/requirements.txt
            python -m pip install -r remote_vector_index_builder/app/requirements.txt
            python -m pip install -r test_remote_vector_index_builder/requirements.txt
            python -m pip install -r e2e/api/requirements.txt

        - name: Run Linting - flake8
          run: |
            python -m flake8 remote_vector_index_builder/ test_remote_vector_index_builder/ e2e/

        - name: Run Formatter - black
          run: |
            python -m black --check remote_vector_index_builder/ test_remote_vector_index_builder/ e2e/

        - name: Run Type Checker - mypy
          run: |
            python -m mypy remote_vector_index_builder/ test_remote_vector_index_builder/ e2e/
        - name: Run tests
          run: |
            python -m pytest test_remote_vector_index_builder/
